### ISSUE TITLE
re-frame complains about no handler for :on-failure

### ISSUE THREAD

**Issue by sooheon** [ingesolvoll/re-chain#1]
```
re-frame: no – ":event" – "handler registered for:"
Keyword

_hash: 962976084
cljs$lang$protocol_mask$partition0$: 2153775105
cljs$lang$protocol_mask$partition1$: 4096
fqn: "http-no-on-failure"
name: "http-no-on-failure"
ns: null
```

This can be solved by adding a `:on-failure` event vector to the `:http-xhrio` map, of course, but maybe this should be shown in the example?

**Comment by ingesolvoll** [comment]
Definitely agree, will fix!

Thanks for reporting!

**Comment by sooheon** [comment]
More warnings; I'm not familiar with interceptors so not sure how to proceed.

```
[Error] re-frame: no handler registered for effect: (2)
P
L: 4096
bd: 301435442
ja: "event"
m: 2153775105
name: "event"
pb: null

P Prototype
". Ignoring."
	error
	hh (app.js:585:383)
	gh (app.js:585:305)
	fh (app.js:585:223)
	h (app.js:591:123)
	WV (app.js:1631:205)
	(anonymous function) (app.js:1641:405)
	eW (app.js:1633:172)
	pW (app.js:1634:1090)
	wW (app.js:1639:191)
	uW (app.js:1635:292)
	(anonymous function) (app.js:1636:484)
	vW (app.js:1639)
	(anonymous function) (app.js:1635:409)
	onmessage (app.js:1058:298)
```

```
[Error] re-frame: no handler registered for effect: (2)
P
L: 4096
bd: -840935075
ja: "re-frame.std-interceptors/untrimmed-event"
m: 2153775105
name: "untrimmed-event"
pb: "re-frame.std-interceptors"

P Prototype
". Ignoring."
	error
	hh (app.js:585:383)
	gh (app.js:585:305)
	fh (app.js:585:223)
	h (app.js:591:123)
	WV (app.js:1631:205)
	(anonymous function) (app.js:1641:405)
	eW (app.js:1633:172)
	pW (app.js:1634:1090)
	wW (app.js:1639:191)
	uW (app.js:1635:292)
	(anonymous function) (app.js:1636:484)
	vW (app.js:1639)
	(anonymous function) (app.js:1635:409)
	onmessage (app.js:1058:298)
```

**Comment by ingesolvoll** [comment]
Hard to tell what this is without getting more context. Could you try the following?
* Compile your CLJS without optimizations, so we get more debuggable code
* Post the error message here
* Then try to remove code until we now which part is causing the error.

**Comment by ingesolvoll** [comment]
From what I can see in the error, your event handler is returning a map that has (2) as one of the keys. Could you confirm if this is true or not?

**Comment by sooheon** [comment]
Without optimizations, the two errors look like this:

```
core.cljs:3874 re-frame: no handler registered for effect: :event . Ignoring.
[...]
core.cljs:3874 re-frame: no handler registered for effect: :re-frame.std-interceptors/untrimmed-event . Ignoring.
```

So the effect keys are `:event` and `:re-frame.std-interceptors/untrimmed-event`, neither of which I've defined.

**Comment by ingesolvoll** [comment]
I'm thinking that this is not an error inside re-chain, but a code error towards re-frame. But hard to be sure without seeing the source code.

I would recommend debugging this by deleting your code, line by line, until you see the errors disappearing.

**Comment by ingesolvoll** [comment]
I would love to see the source code for this, as there might be potential for re-chain to give nice error message for common code errors.

**Comment by sooheon** [comment]
I figured it out! And sorry, it did turn out to be user error :)

Basically I had a `:reg-chain` like so:

```
(k/reg-chain
 ::load-models
 (fn [_ _]
   {:http-xhrio (assoc default-req :uri "/api/models")})
 (fn [ctx [_ models]]
   (-> ctx
       (assoc-in [:db :models] models)
       (assoc-in [:db :annotation-config :model] (first models)))))

```

As you can see, the `ctx` I was returning with the last link in the chain had multiple keys other than `:db`, which were not relevant and had no corresponding handlers.

**Comment by ingesolvoll** [comment]
Glad you figured it out, and thank you again for reporting the initial inconsistency :)
