### ISSUE TITLE
Allow non-sequence interceptors

### ISSUE THREAD

**Issue by nilern** [ingesolvoll/re-chain#4]
Re-frame `reg-event-*` accept a single interceptor as well as (nested) sequences of interceptors, but re-chain expects `user-interceptors` to be sequence (by using `concat` on it). This has led to puzzling moments when changing `reg-event-fx`:s to `reg-chain*`:s.

**Comment by ingesolvoll** [comment]
I actually did not know that. I think I solved the problem with the linked commits
