### ISSUE TITLE
`replace-pointers` is slow

### ISSUE THREAD

**Issue by nilern** [ingesolvoll/re-chain#5]
The effects map is not necessarily small, for example it might contain the response from a previous HTTP request and `postwalk` obviously is O(n). And this cost has to be paid even when the `:chain/next` feature is not used. Indeed, I did not know such a feature even existed until my coworker found that the postwalk was causing serious performance issues.

**Comment by ingesolvoll** [comment]
@nilern Thanks, that's a good catch! Did not have time to look into this yet, do you have ideas for alternative approaches?

**Comment by nilern** [comment]
A quick fix would be making it possible to turn the feature off globally with e.g. `(set! *replace-pointers* false)`. That is very crude. I would prefer that the feature be off by default and could be enabled for chains that actually need it, but I have no specific API in mind and in any case it would be a breaking change.

Maybe the walk could be avoided by making it possible to return a function over the next event instead of an effects map `(fn [next-event] {:db ...`. I do not know how that could be supported, especially without relying on re-frame implementation details.

**Comment by ingesolvoll** [comment]
In case of breaking change, I think I would prefer turning it off by default, and using your suggestion `(set! *replace-pointers* false)`.  For the few apps actually using this feature, it will be obvious that the error is related to this keyword.

**Comment by nilern** [comment]
Thanks a lot for fixing all my issues! And I hope my initial frustration did not show too much :sweat_smile:

**Comment by ingesolvoll** [comment]
@nilern No problem, and thanks for the feedback! Those were significant issues, and quality is definitely higher now.
