### ISSUE TITLE
Using spec.alpha and expound brings lots of code into JS bundle

### ISSUE THREAD

**Issue by Deraen** [ingesolvoll/re-chain#6]
Just a heads up, when using re-chain in a project without Spec or Expound, using them here brings about 135KB JS code to the project (before gzip).

Not sure if would make sense to validate parameters without them, or make the validation optional somehow. Might be possible to wrap expound calls in compile time checks against `goog.DEBUG` or separate constant. Not sure if DCE is good enough to remove whole spec and expound then.

![image](https://user-images.githubusercontent.com/648087/108703439-4c4ee780-7513-11eb-91eb-0d84a0266674.png)

**Comment by Deraen** [comment]
As spec is also used to conform the values, the calls can't just be disabled in the production builds.

**Comment by ingesolvoll** [comment]
Hm, never considered this before. 135kb is pretty outrageous :)

I suppose one alternative is to switch to malli, I need to look over the code when I have the time. I do want to have user friendly error messages on this, so I would prefer a solution that doesn't remove it.

**Comment by Deraen** [comment]
If you look at the report, Malli doesn't do much better on the output size currently. Might be improved later, but Closure can't optimize Cljs protocols and reifies very efficiently.

Unfortunately currently Cljs libraries need to consider how important output size is, and if they can be implemented without e.g. conform. Which is a shame since Conform and Malli regexs are definitely useful for parsing parameters. Not sure of all cases here, but simple `(partition 2 coll)` would take care of some of those `s/cat`.

**Comment by ingesolvoll** [comment]
Solution is ready, with some custom loops to parse manually.
